// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IBoardFields {
  /** Name */
  name: string;

  /** Order */
  order: number;

  /** Title */
  title: string;

  /** Image */
  image: Asset;

  /** Biography */
  biography: Document;
}

export interface IBoard extends Entry<IBoardFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'board';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IGranteeFields {
  /** Name */
  name: string;

  /** Url */
  url: string;

  /** Image */
  image: Asset;

  /** Description */
  description: Document;

  /** Order */
  order: number;
}

export interface IGrantee extends Entry<IGranteeFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'grantee';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'board' | 'grantee';

export type IEntry = IBoard | IGrantee;

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
