// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IBoardFields {
  /** Name */
  name: string;

  /** Order */
  order: number;

  /** Title */
  title: string;

  /** Image */
  image: Asset;

  /** Biography */
  biography: Document;
}

export interface IBoard extends Entry<IBoardFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'board';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IEndowmentFields {
  /** Balance */
  balance: number;

  /** Date */
  date: string;

  /** Note */
  note?: string | undefined;
}

/** The ongoing balance of the endowment */

export interface IEndowment extends Entry<IEndowmentFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'endowment';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IGrantFields {
  /** Date */
  date: string;

  /** Amount */
  amount: number;

  /** Grantee */
  grantee: IGrantee;

  /** Note */
  note: string;
}

/** Amounts given to grantees */

export interface IGrant extends Entry<IGrantFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'grant';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IGranteeFields {
  /** Name */
  name: string;

  /** Url */
  url: string;

  /** Image */
  image: Asset;

  /** Description */
  description: Document;

  /** Order */
  order: number;
}

export interface IGrantee extends Entry<IGranteeFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'grantee';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE = 'board' | 'endowment' | 'grant' | 'grantee';

export type IEntry = IBoard | IEndowment | IGrant | IGrantee;

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
